# Generated by Django 3.2.7 on 2021-09-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myparser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allowance',
            new_name='Tolerances',
        ),
        migrations.AlterModelOptions(
            name='devicegroup',
            options={'ordering': ['device_group']},
        ),
        migrations.AlterModelOptions(
            name='tolerances',
            options={'ordering': ['tolerances']},
        ),
        migrations.AlterModelOptions(
            name='welder',
            options={'ordering': ['brand']},
        ),
        migrations.AlterField(
            model_name='groupmaterialwelded',
            name='group_material_welded',
            field=models.CharField(choices=[('M 01', 'M 01'), ('M 02', 'M 02'), ('M 03', 'M 03'), ('M 05', 'M 05'), ('M 11', 'M 11')], max_length=60),
        ),
        migrations.RemoveField(
            model_name='groupmaterialwelded',
            name='welder',
        ),
        migrations.AddField(
            model_name='groupmaterialwelded',
            name='welder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myparser.welder'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='typedetails',
            name='welder',
        ),
        migrations.AddField(
            model_name='typedetails',
            name='welder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myparser.welder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typesmaterial',
            name='types_material',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='typesmaterial',
            name='welder',
        ),
        migrations.AddField(
            model_name='typesmaterial',
            name='welder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myparser.welder'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='typewelding',
            name='welder',
        ),
        migrations.AddField(
            model_name='typewelding',
            name='welder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myparser.welder'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='weldingposition',
            name='welder',
        ),
        migrations.AddField(
            model_name='weldingposition',
            name='welder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myparser.welder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weldingposition',
            name='welding_position',
            field=models.CharField(max_length=10),
        ),
    ]
