# Generated by Django 3.2.7 on 2021-09-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myparser', '0003_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='book',
            new_name='file',
        ),
    ]
